channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=24.3.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==2.1.1
  - pandas==2.2.3
  - pyarrow==18.1.0
  - scikit-learn==1.8.0
  - scipy==1.15.3
  - xgboost==3.1.2
name: mlflow-env
